{"kind":"symbol","topicSections":[{"title":"Introduction","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/GettingStarted"]},{"title":"Sample projects","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DateParsing","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataParsing"],"title":"String extensions for quick data parsing"},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Calculator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/RawExpression"],"title":"Doing calculations"},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection"],"title":"Doing multi-line calculations"},{"title":"Results of calculation","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EmptyResult","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError"]},{"title":"Result formatting","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/FormattingPreferences","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyFormattingPreferences","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/NotationPreferences","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SIThreshold","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Scalar","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultConversionBehavior","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultConversionRule","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitSymbolReplacement","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResultFormatter"]},{"title":"Setting variables in calculation","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Variable","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableName","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableValue","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableList"]},{"title":"Customizing the behavior of calculator or line collection","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineCustomization","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineFeatureFlags","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Holiday","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomUnit","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitMeasurementSystem","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ExpressionBeautificationOptions"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyRateProvider","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyRateRequest","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ECBCurrencyRateProvider"],"title":"Providing live currency rates"},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WeatherDataProvider","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WeatherDataRequest"],"title":"Providing live weather data"},{"title":"Detailed information about how an expression was interpreted","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenType","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenSubType","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Token","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenList","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenListMetadata","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenListForm","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenTypeSet","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenIndex","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenIndexPath"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitType","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitIdentifier","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/FunctionIdentifier","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/StatisticType"],"title":"Enums used by SoulverCore"},{"title":"Custom data types used by SoulverCore","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Percentage","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Fraction","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Multiplier","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SalesTax","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitExpression","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SCUnit","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitRange","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DegreesMinutesSeconds","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/GPSCoordinates","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Substance","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitRate","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PercentageRate","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DecimalRate","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Datestamp","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Datespan","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Timespan","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Frametime","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Laptime","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Timestamp","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/iso8601","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Resolution","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/List","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Pitch","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PitchNotation"]},{"title":"Currencies & places (timezones)","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyList","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyCode","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Place","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Airport","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/City","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Country","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/StaticResouces"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionArchive","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionArchiver","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionExporter","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionCompletions","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionFuser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionReducer","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionTrimmer","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionEnumerator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionIterator"],"title":"Line collection utilities"},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Line","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineIndex","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineSheet","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineSheetDelta","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Subsheet"],"abstract":[{"type":"text","text":"The backing store for data in a LineCollection"}],"title":"Lines & sheets"},{"abstract":[{"type":"text","text":"Used to reference previous lines in a LineCollection"}],"title":"Line references","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineReference","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UntokenizedLineReference","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineAboveReference","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UID","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SingleCharacterUIDGenerator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrivateUnicodeSymbol"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultCollection","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultPercentageCalculator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultContextualMetadata","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultOperations"],"title":"Result utilities"},{"title":"Custom function support","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunction","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionHandler","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrototypeExpression","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BackgroundCustomFunctionHandler","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomType","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrototypePlaceholder","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionDefinitionUtility","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionParameter"]},{"title":"String parsing extension support","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataPoint","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DateFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/NumberFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WhitespaceFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BinaryNumberFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/OctalNumberFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/HexNumberFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BooleanFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PercentageFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyCodeFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SubstanceFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitOfTypeFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LaptimeFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/iso8601FromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimecodeFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimespanFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnixTimestampFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PitchFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ScreenResolutionFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimeZoneFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PlaceFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/AirportFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EmailFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/URLFromTokenParser","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/HashtagFromTokenParser"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/MisplacedThousandsSeparatorBehavior"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Foundation","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Swift"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/soulvercore"]}],"metadata":{"role":"collection","title":"SoulverCore","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"SoulverCore"}],"externalID":"SoulverCore"},"sections":[],"abstract":[{"type":"text","text":"A powerful natural language calculation engine"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"identifier":"SoulverCoreIcon.png","type":"image"}]},{"inlineContent":[{"type":"text","text":"SoulverCore is a math engine that calculates day-to-day mathematical expressions.  It powers the popular Mac & iPad notepad calculator app "},{"isActive":true,"type":"reference","identifier":"https:\/\/soulver.app"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"heading","anchor":"Key-Classes","text":"Key Classes","level":2},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"To calculate the result of a single mathematical expression, use "},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Calculator","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To do multi-line calculations (like "},{"identifier":"https:\/\/soulver.app","overridingTitle":"Soulver","overridingTitleInlineContent":[{"text":"Soulver","type":"text"}],"type":"reference","isActive":true},{"text":") use ","type":"text"},{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"To customize the way your expression is interpreted, use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineCustomization"},{"text":" and\/or a ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableList","isActive":true}]}]},{"content":[{"inlineContent":[{"text":"To customize the way a result is formatted, use ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/FormattingPreferences","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Design-Goals","type":"heading","level":2,"text":"Design Goals"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Sensible defaults for most use-cases (common tasks work out-of-the-box)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A high level of customizability (non-common tasks are possible, like adding new phrase functions & custom units)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Excellent performance (< 0.5 ms per calculation)"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[[]]},"references":{"doc://app.soulver.core/documentation/SoulverCore/PitchNotation":{"url":"\/documentation\/soulvercore\/pitchnotation","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PitchNotation","kind":"identifier"}],"abstract":[{"type":"text","text":"A string formatted in standard pitch notation"}],"navigatorTitle":[{"kind":"identifier","text":"PitchNotation"}],"type":"topic","title":"PitchNotation","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PitchNotation","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/CustomFunctionParameter":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionParameter","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/customfunctionparameter","abstract":[{"text":"Represents a parameter to a custom function","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomFunctionParameter"}],"title":"CustomFunctionParameter","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomFunctionParameter","kind":"identifier"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/UntokenizedLineReference":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UntokenizedLineReference","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/untokenizedlinereference","abstract":[{"type":"text","text":"A localized string representing a plain text reference to a previous line"}],"title":"UntokenizedLineReference","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UntokenizedLineReference"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Percentage":{"url":"\/documentation\/soulvercore\/percentage","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Percentage","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a percentage"}],"navigatorTitle":[{"kind":"identifier","text":"Percentage"}],"type":"topic","title":"Percentage","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Percentage","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EngineFeatureFlags":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EngineFeatureFlags"}],"kind":"symbol","abstract":[{"type":"text","text":"Customize the behaviour of SoulverCore’s math engine with these flags"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineFeatureFlags","role":"symbol","type":"topic","title":"EngineFeatureFlags","navigatorTitle":[{"text":"EngineFeatureFlags","kind":"identifier"}],"url":"\/documentation\/soulvercore\/enginefeatureflags"},"doc://app.soulver.core/documentation/SoulverCore/BinaryNumberFromTokenParser":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BinaryNumberFromTokenParser"}],"url":"\/documentation\/soulvercore\/binarynumberfromtokenparser","abstract":[],"title":"BinaryNumberFromTokenParser","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BinaryNumberFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BinaryNumberFromTokenParser","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/RawExpression":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RawExpression","kind":"identifier"}],"url":"\/documentation\/soulvercore\/rawexpression","type":"topic","role":"symbol","kind":"symbol","title":"RawExpression","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/RawExpression","abstract":[{"type":"text","text":"A string representing a mathematical expression you’d like to be evaluated with SoulverCore"}],"navigatorTitle":[{"text":"RawExpression","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/PrototypeExpression":{"navigatorTitle":[{"kind":"identifier","text":"PrototypeExpression"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrototypeExpression","kind":"symbol","title":"PrototypeExpression","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"PrototypeExpression","kind":"identifier"}],"url":"\/documentation\/soulvercore\/prototypeexpression","type":"topic","abstract":[{"type":"text","text":"A special “regex-like” SoulverCore string format that includes placeholders which represent types of tokens to match"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineCollection":{"url":"\/documentation\/soulvercore\/linecollection","title":"LineCollection","kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","abstract":[{"type":"text","text":"Perform calculations across multiple lines"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineCollection"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LineCollection"}]},"doc://app.soulver.core/documentation/SoulverCore/DataFromTokenParser":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataFromTokenParser","url":"\/documentation\/soulvercore\/datafromtokenparser","kind":"symbol","role":"symbol","abstract":[{"text":"DataFromTokenParser will attempt to parse its given data type from a token it","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataFromTokenParser","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DataFromTokenParser","kind":"identifier"}],"title":"DataFromTokenParser"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionArchive":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LineCollectionArchive","kind":"identifier"}],"abstract":[{"type":"text","text":"A codable type that encodes\/decodes a "},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"LineCollectionArchive"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionArchive","title":"LineCollectionArchive","url":"\/documentation\/soulvercore\/linecollectionarchive"},"doc://app.soulver.core/documentation/SoulverCore/LaptimeFromTokenParser":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LaptimeFromTokenParser","navigatorTitle":[{"text":"LaptimeFromTokenParser","kind":"identifier"}],"type":"topic","title":"LaptimeFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LaptimeFromTokenParser","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/soulvercore\/laptimefromtokenparser","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SoulverCoreVersionNumber":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SoulverCoreVersionNumber","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/soulvercoreversionnumber","abstract":[{"type":"text","text":"Project version number for SoulverCore."}],"title":"SoulverCoreVersionNumber","fragments":[{"text":"SoulverCoreVersionNumber","kind":"identifier"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Datespan":{"role":"symbol","abstract":[{"type":"text","text":"A SoulverCore datatype representing a span of dates"}],"title":"Datespan","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Datespan","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Datespan"}],"type":"topic","url":"\/documentation\/soulvercore\/datespan","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Datespan"}]},"doc://app.soulver.core/documentation/SoulverCore/TokenSubType":{"type":"topic","abstract":[{"type":"text","text":"Even more detail captured by the parser about various subtypes that a particular token can be"}],"role":"symbol","title":"TokenSubType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TokenSubType","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenSubType","url":"\/documentation\/soulvercore\/tokensubtype","navigatorTitle":[{"text":"TokenSubType","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/CurrencyFormattingPreferences":{"url":"\/documentation\/soulvercore\/currencyformattingpreferences","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CurrencyFormattingPreferences","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"CurrencyFormattingPreferences","navigatorTitle":[{"text":"CurrencyFormattingPreferences","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyFormattingPreferences"},"doc://app.soulver.core/documentation/SoulverCore/iso8601":{"type":"topic","abstract":[{"type":"text","text":"A SoulverCore datatype representing an iso8601 formatted point in time"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"iso8601","kind":"identifier"}],"url":"\/documentation\/soulvercore\/iso8601","navigatorTitle":[{"text":"iso8601","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/iso8601","title":"iso8601"},"doc://app.soulver.core/documentation/SoulverCore/BackgroundCustomFunctionHandler":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BackgroundCustomFunctionHandler","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/backgroundcustomfunctionhandler","abstract":[{"text":"A variant of the custom function handler that supports async\/await","type":"text"}],"navigatorTitle":[{"text":"BackgroundCustomFunctionHandler","kind":"identifier"}],"title":"BackgroundCustomFunctionHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundCustomFunctionHandler"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionCompletions":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LineCollectionCompletions","kind":"identifier"}],"abstract":[{"type":"text","text":"This class is useful for implementing auto-complete of variable names."}],"navigatorTitle":[{"text":"LineCollectionCompletions","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionCompletions","title":"LineCollectionCompletions","url":"\/documentation\/soulvercore\/linecollectioncompletions"},"doc://app.soulver.core/documentation/SoulverCore/SingleCharacterUIDGenerator":{"abstract":[{"text":"Generates a unique UID with a single character","type":"text"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SingleCharacterUIDGenerator","title":"SingleCharacterUIDGenerator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SingleCharacterUIDGenerator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SingleCharacterUIDGenerator","kind":"identifier"}],"url":"\/documentation\/soulvercore\/singlecharacteruidgenerator","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionReducer":{"kind":"symbol","title":"LineCollectionReducer","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionReducer","navigatorTitle":[{"text":"LineCollectionReducer","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCollectionReducer"}],"abstract":[{"text":"Reduces a line collection to a single value or set of values","type":"text"}],"type":"topic","url":"\/documentation\/soulvercore\/linecollectionreducer"},"doc://app.soulver.core/documentation/SoulverCore/Frametime":{"url":"\/documentation\/soulvercore\/frametime","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Frametime","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a moment in time in a piece of video content"}],"navigatorTitle":[{"kind":"identifier","text":"Frametime"}],"type":"topic","title":"Frametime","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Frametime","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TimespanFromTokenParser":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"TimespanFromTokenParser","kind":"identifier"}],"title":"TimespanFromTokenParser","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimespanFromTokenParser","url":"\/documentation\/soulvercore\/timespanfromtokenparser","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimespanFromTokenParser"}]},"doc://app.soulver.core/documentation/SoulverCore/PitchFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/pitchfromtokenparser","navigatorTitle":[{"text":"PitchFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PitchFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PitchFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"PitchFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Place":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Place","kind":"identifier"}],"abstract":[{"text":"An object representing a place that can be used as a timezone","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To support custom places in your expressions, set the “customPlaces” property on the EngineCustomization"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Place","type":"topic","title":"Place","url":"\/documentation\/soulvercore\/place","navigatorTitle":[{"text":"Place","kind":"identifier"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Datestamp":{"type":"topic","url":"\/documentation\/soulvercore\/datestamp","abstract":[{"type":"text","text":"A SoulverCore datatype representing a point in time with associated metadata"}],"kind":"symbol","title":"Datestamp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Datestamp","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Datestamp"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Datestamp","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SoulverCoreVersionString":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SoulverCoreVersionString","fragments":[{"text":"SoulverCoreVersionString","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Project version string for SoulverCore."}],"kind":"symbol","title":"SoulverCoreVersionString","url":"\/documentation\/soulvercore\/soulvercoreversionstring","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"url":"\/documentation\/soulvercore\/evaluationresult","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Represents the underlying data of a result of a SoulverCore calculation"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationResult"}],"title":"EvaluationResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationResult"}]},"doc://app.soulver.core/documentation/SoulverCore/Holiday":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Holiday","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a public holiday on a particular date"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Holiday","url":"\/documentation\/soulvercore\/holiday","role":"symbol","navigatorTitle":[{"text":"Holiday","kind":"identifier"}],"title":"Holiday","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/WhitespaceFromTokenParser":{"navigatorTitle":[{"text":"WhitespaceFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WhitespaceFromTokenParser","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WhitespaceFromTokenParser"}],"title":"WhitespaceFromTokenParser","kind":"symbol","url":"\/documentation\/soulvercore\/whitespacefromtokenparser"},"doc://app.soulver.core/documentation/SoulverCore/LineSheetDelta":{"abstract":[{"type":"text","text":"A simple data structure to represent the changes from one state of a line sheet to another"}],"navigatorTitle":[{"text":"LineSheetDelta","kind":"identifier"}],"url":"\/documentation\/soulvercore\/linesheetdelta","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineSheetDelta"}],"title":"LineSheetDelta","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineSheetDelta"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionIterator":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineCollectionIterator"}],"abstract":[{"type":"text","text":"Add iteration support to line collection"}],"navigatorTitle":[{"kind":"identifier","text":"LineCollectionIterator"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionIterator","title":"LineCollectionIterator","url":"\/documentation\/soulvercore\/linecollectioniterator"},"doc://app.soulver.core/documentation/SoulverCore/UnitType":{"url":"\/documentation\/soulvercore\/unittype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UnitType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitType","role":"symbol","title":"UnitType","abstract":[{"type":"text","text":"A list of the unit categories supported by SoulverCore"}],"navigatorTitle":[{"kind":"identifier","text":"UnitType"}]},"doc://app.soulver.core/documentation/SoulverCore/StatisticType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StatisticType","kind":"identifier"}],"kind":"symbol","title":"StatisticType","url":"\/documentation\/soulvercore\/statistictype","type":"topic","abstract":[{"type":"text","text":"All the types of statistics that SoulverCore supports"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/StatisticType","navigatorTitle":[{"text":"StatisticType","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/CustomUnit":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomUnit","kind":"identifier"}],"abstract":[{"text":"A model object representing a custom unit","type":"text"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomUnit","url":"\/documentation\/soulvercore\/customunit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomUnit"}],"title":"CustomUnit","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/DecimalRate":{"url":"\/documentation\/soulvercore\/decimalrate","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DecimalRate","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a rate of some amount per unit"}],"navigatorTitle":[{"kind":"identifier","text":"DecimalRate"}],"type":"topic","title":"DecimalRate","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DecimalRate","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineSheet":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"LineSheet","kind":"identifier"}],"url":"\/documentation\/soulvercore\/linesheet","abstract":[{"type":"text","text":"A basic encodable model object that contains a list of "},{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Line","isActive":true,"type":"reference"},{"type":"text","text":" objects"}],"title":"LineSheet","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineSheet","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineSheet"}]},"doc://app.soulver.core/documentation/SoulverCore/Token":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Token","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Token","kind":"identifier"}],"navigatorTitle":[{"text":"Token","kind":"identifier"}],"type":"topic","url":"\/documentation\/soulvercore\/token","title":"Token","abstract":[{"text":"A token represents a meaningful element in a math expression (like a number, operator, unit, etc)","type":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/MisplacedThousandsSeparatorBehavior":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/MisplacedThousandsSeparatorBehavior","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/misplacedthousandsseparatorbehavior","abstract":[{"type":"text","text":"Choose your desired behavior for how to handle numbers with misplaced thousands separators"}],"navigatorTitle":[{"text":"MisplacedThousandsSeparatorBehavior","kind":"identifier"}],"title":"MisplacedThousandsSeparatorBehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MisplacedThousandsSeparatorBehavior","kind":"identifier"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/AirportFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/airportfromtokenparser","navigatorTitle":[{"text":"AirportFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/AirportFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AirportFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"AirportFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Pitch":{"url":"\/documentation\/soulvercore\/pitch","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pitch","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore data type representing a musical pitch"}],"navigatorTitle":[{"kind":"identifier","text":"Pitch"}],"type":"topic","title":"Pitch","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Pitch","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/CurrencyCodeFromTokenParser":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CurrencyCodeFromTokenParser"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyCodeFromTokenParser","title":"CurrencyCodeFromTokenParser","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"CurrencyCodeFromTokenParser","kind":"identifier"}],"url":"\/documentation\/soulvercore\/currencycodefromtokenparser"},"doc://app.soulver.core/documentation/SoulverCore/UnitExpression":{"navigatorTitle":[{"kind":"identifier","text":"UnitExpression"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitExpression","kind":"symbol","title":"UnitExpression","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnitExpression"}],"url":"\/documentation\/soulvercore\/unitexpression","abstract":[{"type":"text","text":"SoulverCore datatype representing a unit with a value"}]},"doc://app.soulver.core/documentation/SoulverCore/UnitRate":{"url":"\/documentation\/soulvercore\/unitrate","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"UnitRate","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a unit rate"}],"navigatorTitle":[{"kind":"identifier","text":"UnitRate"}],"type":"topic","title":"UnitRate","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitRate","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SIThreshold":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SIThreshold","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents various magnitudes for use in notation formatting","type":"text"}],"url":"\/documentation\/soulvercore\/sithreshold","navigatorTitle":[{"kind":"identifier","text":"SIThreshold"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SIThreshold","title":"SIThreshold"},"doc://app.soulver.core/documentation/SoulverCore/PrivateUnicodeSymbol":{"abstract":[{"text":"A single character from the private section of Unicode","type":"text"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrivateUnicodeSymbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PrivateUnicodeSymbol","kind":"identifier"}],"navigatorTitle":[{"text":"PrivateUnicodeSymbol","kind":"identifier"}],"role":"symbol","url":"\/documentation\/soulvercore\/privateunicodesymbol","type":"topic","title":"PrivateUnicodeSymbol"},"doc://app.soulver.core/documentation/SoulverCore/ExpressionBeautificationOptions":{"title":"ExpressionBeautificationOptions","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionBeautificationOptions"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ExpressionBeautificationOptions","url":"\/documentation\/soulvercore\/expressionbeautificationoptions","abstract":[{"type":"text","text":"A set of options for ‘beautifying’ a mathematical expression"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExpressionBeautificationOptions"}],"type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/VariableValue":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"VariableValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A variable value, like “123.45”,"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableValue","type":"topic","title":"VariableValue","url":"\/documentation\/soulvercore\/variablevalue","navigatorTitle":[{"text":"VariableValue","kind":"identifier"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/ResultCollection":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultCollection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultCollection"}],"title":"ResultCollection","url":"\/documentation\/soulvercore\/resultcollection","navigatorTitle":[{"kind":"identifier","text":"ResultCollection"}],"kind":"symbol","abstract":[{"type":"text","text":"Performs basic statistical operations on an array of "},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult","type":"reference"},{"type":"text","text":" objects"}],"role":"symbol","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/FormattingPreferences":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/FormattingPreferences","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormattingPreferences"}],"kind":"symbol","url":"\/documentation\/soulvercore\/formattingpreferences","type":"topic","navigatorTitle":[{"text":"FormattingPreferences","kind":"identifier"}],"abstract":[{"text":"A configuration object used to specify how you want SoulverCore to format results","type":"text"}],"title":"FormattingPreferences"},"doc://app.soulver.core/documentation/SoulverCore/EmailFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/emailfromtokenparser","navigatorTitle":[{"text":"EmailFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EmailFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailFromTokenParser"}],"type":"topic","abstract":[],"title":"EmailFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/ScreenResolutionFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/screenresolutionfromtokenparser","navigatorTitle":[{"text":"ScreenResolutionFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ScreenResolutionFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ScreenResolutionFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"ScreenResolutionFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineAboveReference":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineAboveReference","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/lineabovereference","abstract":[{"type":"text","text":"A localized string representing a plain text reference to the line above previous line"}],"title":"LineAboveReference","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"LineAboveReference","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Swift":{"abstract":[],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Swift","url":"\/documentation\/soulvercore\/swift","title":"Swift"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationError":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError","abstract":[{"type":"text","text":"All errors that SoulverCore can produce as a result of a calculation"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationError"}],"title":"EvaluationError","role":"symbol","navigatorTitle":[{"text":"EvaluationError","kind":"identifier"}],"url":"\/documentation\/soulvercore\/evaluationerror","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/UnitIdentifier":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitIdentifier","navigatorTitle":[{"text":"UnitIdentifier","kind":"identifier"}],"title":"UnitIdentifier","url":"\/documentation\/soulvercore\/unitidentifier","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnitIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A list of all the standard units supported by SoulverCore"}]},"doc://app.soulver.core/documentation/SoulverCore/VariableList":{"url":"\/documentation\/soulvercore\/variablelist","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableList","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A list of variables (single words or phrases) and their values"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VariableList","kind":"identifier"}],"title":"VariableList","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VariableList"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResultFormatter":{"abstract":[{"type":"text","text":"Quickly turn an "},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","type":"reference"},{"type":"text","text":" into a "},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult","isActive":true}],"role":"symbol","title":"EvaluationResultFormatter","url":"\/documentation\/soulvercore\/evaluationresultformatter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationResultFormatter"}],"navigatorTitle":[{"kind":"identifier","text":"EvaluationResultFormatter"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResultFormatter"},"doc://app.soulver.core/documentation/SoulverCore/NumberFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/numberfromtokenparser","navigatorTitle":[{"text":"NumberFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/NumberFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NumberFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"NumberFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SCUnit":{"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SCUnit","kind":"symbol","role":"symbol","title":"SCUnit","abstract":[{"text":"A SoulverCore datatype that represents a unit","type":"text"}],"url":"\/documentation\/soulvercore\/scunit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SCUnit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SCUnit"}]},"doc://app.soulver.core/documentation/SoulverCore/Subsheet":{"type":"topic","url":"\/documentation\/soulvercore\/subsheet","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Subsheet","role":"symbol","abstract":[{"type":"text","text":"A subsheet is a sheet that is referenced by a line collection"}],"navigatorTitle":[{"kind":"identifier","text":"Subsheet"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Subsheet","kind":"identifier"}],"title":"Subsheet","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Resolution":{"url":"\/documentation\/soulvercore\/resolution","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Resolution","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing  resoluton of a display or image (width x height)"}],"navigatorTitle":[{"kind":"identifier","text":"Resolution"}],"type":"topic","title":"Resolution","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Resolution","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Timespan":{"url":"\/documentation\/soulvercore\/timespan","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Timespan","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype that represents a collection of discrete quantities of time together (like 3 days, 2 hours, 20 minutes)."}],"navigatorTitle":[{"kind":"identifier","text":"Timespan"}],"type":"topic","title":"Timespan","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Timespan","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/StaticResouces":{"abstract":[{"type":"text","text":"Represents the JSON loadable bundle resources that are present in the SoulverCore bundle"}],"title":"StaticResouces","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/StaticResouces","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticResouces","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StaticResouces"}],"url":"\/documentation\/soulvercore\/staticresouces"},"doc://app.soulver.core/documentation/SoulverCore/FunctionIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"FunctionIdentifier"}],"url":"\/documentation\/soulvercore\/functionidentifier","type":"topic","title":"FunctionIdentifier","role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/FunctionIdentifier","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FunctionIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"A list of all standard word functions supported by SoulverCore"}]},"doc://app.soulver.core/documentation/SoulverCore/WeatherDataProvider":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WeatherDataProvider","url":"\/documentation\/soulvercore\/weatherdataprovider","type":"topic","abstract":[{"type":"text","text":"WeatherDataProvider is an object that provides weather data for queries expressed in word functions"}],"title":"WeatherDataProvider","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WeatherDataProvider","kind":"identifier"}],"navigatorTitle":[{"text":"WeatherDataProvider","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/TokenIndex":{"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TokenIndex","kind":"identifier"}],"abstract":[{"text":"The index of a token in a ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenList","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"TokenIndex"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenIndex","title":"TokenIndex","role":"symbol","url":"\/documentation\/soulvercore\/tokenindex"},"doc://app.soulver.core/documentation/SoulverCore/UnitSymbolReplacement":{"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitSymbolReplacement","url":"\/documentation\/soulvercore\/unitsymbolreplacement","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnitSymbolReplacement"}],"title":"UnitSymbolReplacement","navigatorTitle":[{"text":"UnitSymbolReplacement","kind":"identifier"}],"abstract":[{"text":"Specify a currency symbol (i.e $) to be used in output formatting instead of a currency code (i.e USD)","type":"text"}],"type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/DataPoint":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataPoint","navigatorTitle":[{"text":"DataPoint","kind":"identifier"}],"type":"topic","title":"DataPoint","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataPoint"}],"abstract":[{"text":"Represents some data you can parse out from a string","type":"text"}],"role":"symbol","url":"\/documentation\/soulvercore\/datapoint","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/DateFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/datefromtokenparser","navigatorTitle":[{"text":"DateFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DateFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateFromTokenParser"}],"type":"topic","abstract":[],"title":"DateFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Country":{"abstract":[{"text":"Represents a country on planet earth","type":"text"}],"title":"Country","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Country","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Country"}],"navigatorTitle":[{"text":"Country","kind":"identifier"}],"url":"\/documentation\/soulvercore\/country"},"doc://app.soulver.core/documentation/SoulverCore/BackgroundEvaluationAndMergingOperation":{"url":"\/documentation\/soulvercore\/backgroundevaluationandmergingoperation","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"BackgroundEvaluationAndMergingOperation","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BackgroundEvaluationAndMergingOperation","title":"BackgroundEvaluationAndMergingOperation"},"doc://app.soulver.core/documentation/SoulverCore/HexNumberFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/hexnumberfromtokenparser","navigatorTitle":[{"text":"HexNumberFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/HexNumberFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HexNumberFromTokenParser"}],"type":"topic","abstract":[],"title":"HexNumberFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionEnumerator":{"abstract":[{"type":"text","text":"A handy class to enumerate expressions and results in a "},{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","isActive":true,"type":"reference"}],"title":"LineCollectionEnumerator","navigatorTitle":[{"text":"LineCollectionEnumerator","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionEnumerator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LineCollectionEnumerator","kind":"identifier"}],"url":"\/documentation\/soulvercore\/linecollectionenumerator"},"doc://app.soulver.core/documentation/SoulverCore/CurrencyList":{"url":"\/documentation\/soulvercore\/currencylist","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CurrencyList","kind":"identifier"}],"title":"CurrencyList","abstract":[{"text":"Use the CurrencyList as a rate provider for hard-coded currency rates","type":"text"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyList","role":"symbol","type":"topic","navigatorTitle":[{"text":"CurrencyList","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/Fraction":{"url":"\/documentation\/soulvercore\/fraction","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Fraction","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a fraction"}],"navigatorTitle":[{"kind":"identifier","text":"Fraction"}],"type":"topic","title":"Fraction","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Fraction","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/PercentageRate":{"url":"\/documentation\/soulvercore\/percentagerate","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PercentageRate","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a rate of some percentage per unit"}],"navigatorTitle":[{"kind":"identifier","text":"PercentageRate"}],"type":"topic","title":"PercentageRate","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PercentageRate","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/PercentageFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/percentagefromtokenparser","navigatorTitle":[{"text":"PercentageFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PercentageFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PercentageFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"PercentageFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/CustomType":{"url":"\/documentation\/soulvercore\/customtype","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomType"}],"navigatorTitle":[{"kind":"identifier","text":"CustomType"}],"title":"CustomType","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomType","abstract":[{"text":"A new ‘thing’ that can be recognized as part of a custom function","type":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/PlaceFromTokenParser":{"title":"PlaceFromTokenParser","abstract":[],"url":"\/documentation\/soulvercore\/placefromtokenparser","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceFromTokenParser"}],"navigatorTitle":[{"text":"PlaceFromTokenParser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PlaceFromTokenParser"},"doc://app.soulver.core/documentation/SoulverCore/EmptyResult":{"url":"\/documentation\/soulvercore\/emptyresult","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmptyResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CalculationResult","kind":"typeIdentifier","preciseIdentifier":"s:11SoulverCore17CalculationResultV"}],"abstract":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult"},{"type":"text","text":" with no data or string representation"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EmptyResult","title":"EmptyResult"},"doc://app.soulver.core/documentation/SoulverCore/CalculationResult":{"abstract":[{"text":"Produced by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Calculator","isActive":true},{"type":"text","text":" or "},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","type":"reference"},{"type":"text","text":" when calculating the result of an expression"}],"role":"symbol","title":"CalculationResult","url":"\/documentation\/soulvercore\/calculationresult","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalculationResult"}],"navigatorTitle":[{"text":"CalculationResult","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionTrimmer":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LineCollectionTrimmer","kind":"identifier"}],"abstract":[{"text":"Removes tokens of a particular type from a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"LineCollectionTrimmer"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionTrimmer","title":"LineCollectionTrimmer","url":"\/documentation\/soulvercore\/linecollectiontrimmer"},"doc://app.soulver.core/documentation/SoulverCore/CurrencyRateProvider":{"type":"topic","title":"CurrencyRateProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CurrencyRateProvider","kind":"identifier"}],"abstract":[{"text":"CurrencyRateProvider is an object that provides currency rates to be used in unit calculations","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/soulvercore\/currencyrateprovider","navigatorTitle":[{"text":"CurrencyRateProvider","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyRateProvider"},"doc://app.soulver.core/documentation/SoulverCore/Line":{"kind":"symbol","navigatorTitle":[{"text":"Line","kind":"identifier"}],"url":"\/documentation\/soulvercore\/line","title":"Line","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Line","kind":"identifier"}],"abstract":[{"text":"A basic model object representing an expression and result","type":"text"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Line","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/UID":{"url":"\/documentation\/soulvercore\/uid","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"UID","kind":"identifier"}],"navigatorTitle":[{"text":"UID","kind":"identifier"}],"title":"UID","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UID","abstract":[{"type":"text","text":"A unique symbol representing a line reference"}]},"doc://app.soulver.core/documentation/SoulverCore/AsynchronousOperation":{"abstract":[{"type":"text","text":"Subclass of "},{"type":"text","text":"Operation"},{"type":"text","text":" that adds support of asynchronous operations."}],"title":"AsynchronousOperation","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/AsynchronousOperation","type":"topic","role":"symbol","url":"\/documentation\/soulvercore\/asynchronousoperation","kind":"symbol","fragments":[{"text":"AsynchronousOperation","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/DegreesMinutesSeconds":{"url":"\/documentation\/soulvercore\/degreesminutesseconds","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DegreesMinutesSeconds","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing a DMS value"}],"navigatorTitle":[{"kind":"identifier","text":"DegreesMinutesSeconds"}],"type":"topic","title":"DegreesMinutesSeconds","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DegreesMinutesSeconds","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Substance":{"url":"\/documentation\/soulvercore\/substance","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Substance","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing a substance"}],"navigatorTitle":[{"kind":"identifier","text":"Substance"}],"type":"topic","title":"Substance","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Substance","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TokenIndexPath":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TokenIndexPath","kind":"identifier"}],"abstract":[{"text":"A coordinate for a token in a ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","isActive":true}],"navigatorTitle":[{"text":"TokenIndexPath","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenIndexPath","title":"TokenIndexPath","role":"symbol","url":"\/documentation\/soulvercore\/tokenindexpath"},"doc://app.soulver.core/documentation/SoulverCore/SampleCalculator":{"url":"\/documentation\/soulvercore\/samplecalculator","role":"sampleCode","type":"topic","kind":"article","abstract":[{"type":"text","text":"Example of adding a quick calculator feature to a Mac or iOS app"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator","title":"Mac & iOS Sample Code"},"doc://app.soulver.core/documentation/SoulverCore/DataParsing":{"role":"article","abstract":[{"type":"text","text":"A declarative & type-safe approach to extracting various data types out of strings"}],"title":"Data from string parsing","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DataParsing","url":"\/documentation\/soulvercore\/dataparsing","kind":"article","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/TimeZoneFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/timezonefromtokenparser","navigatorTitle":[{"text":"TimeZoneFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimeZoneFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeZoneFromTokenParser"}],"type":"topic","abstract":[],"title":"TimeZoneFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TextViewIntegration":{"url":"\/documentation\/soulvercore\/textviewintegration","role":"sampleCode","type":"topic","kind":"article","title":"Add calculation to NSTextView or UITextView","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration","abstract":[{"type":"text","text":"Integrate SoulverCore into the text view of an Mac or iOS app"}]},"doc://app.soulver.core/documentation/SoulverCore/iso8601FromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/iso8601fromtokenparser","navigatorTitle":[{"text":"iso8601FromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/iso8601FromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"iso8601FromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"iso8601FromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TimecodeFromTokenParser":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TimecodeFromTokenParser","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimecodeFromTokenParser"}],"url":"\/documentation\/soulvercore\/timecodefromtokenparser","title":"TimecodeFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimecodeFromTokenParser","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/LineReference":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineReference"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineReference","navigatorTitle":[{"kind":"identifier","text":"LineReference"}],"title":"LineReference","type":"topic","abstract":[{"text":"Wraps a unique ID representing a line reference","type":"text"}],"url":"\/documentation\/soulvercore\/linereference"},"doc://app.soulver.core/documentation/SoulverCore/TokenListMetadata":{"abstract":[{"type":"text","text":"Additional metadata about a parsed expression"}],"url":"\/documentation\/soulvercore\/tokenlistmetadata","type":"topic","title":"TokenListMetadata","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenListMetadata","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TokenListMetadata"}],"navigatorTitle":[{"text":"TokenListMetadata","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/UnitRange":{"url":"\/documentation\/soulvercore\/unitrange","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"UnitRange","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing a range of a particular unit"}],"navigatorTitle":[{"kind":"identifier","text":"UnitRange"}],"type":"topic","title":"UnitRange","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitRange","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/GPSCoordinates":{"url":"\/documentation\/soulvercore\/gpscoordinates","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GPSCoordinates","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing the GPS coordinates of a city or airport"}],"navigatorTitle":[{"kind":"identifier","text":"GPSCoordinates"}],"type":"topic","title":"GPSCoordinates","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/GPSCoordinates","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SalesTax":{"url":"\/documentation\/soulvercore\/salestax","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SalesTax","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing a tax applied at a point of sale"}],"navigatorTitle":[{"kind":"identifier","text":"SalesTax"}],"type":"topic","title":"SalesTax","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SalesTax","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Foundation":{"url":"\/documentation\/soulvercore\/foundation","role":"collection","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Foundation","title":"Foundation"},"doc://app.soulver.core/documentation/SoulverCore/TokenList":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenList"}],"navigatorTitle":[{"text":"TokenList","kind":"identifier"}],"abstract":[{"text":"Contains an array of tokens that represent the various meaningful components of a math expression","type":"text"}],"type":"topic","title":"TokenList","url":"\/documentation\/soulvercore\/tokenlist"},"doc://app.soulver.core/documentation/SoulverCore/UnixTimestampFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/unixtimestampfromtokenparser","navigatorTitle":[{"text":"UnixTimestampFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnixTimestampFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnixTimestampFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"UnixTimestampFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/UnitOfTypeFromTokenParser":{"title":"UnitOfTypeFromTokenParser","abstract":[],"url":"\/documentation\/soulvercore\/unitoftypefromtokenparser","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnitOfTypeFromTokenParser","kind":"identifier"}],"navigatorTitle":[{"text":"UnitOfTypeFromTokenParser","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitOfTypeFromTokenParser"},"doc://app.soulver.core/documentation/SoulverCore/VariableName":{"url":"\/documentation\/soulvercore\/variablename","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/VariableName","role":"symbol","kind":"symbol","abstract":[{"text":"A variable name (can be multiple words)","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"VariableName","kind":"identifier"}],"title":"VariableName","type":"topic","navigatorTitle":[{"text":"VariableName","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore/HashtagFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/hashtagfromtokenparser","navigatorTitle":[{"text":"HashtagFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/HashtagFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HashtagFromTokenParser"}],"type":"topic","abstract":[],"title":"HashtagFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/ResultPercentageCalculator":{"navigatorTitle":[{"kind":"identifier","text":"ResultPercentageCalculator"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultPercentageCalculator","kind":"symbol","url":"\/documentation\/soulvercore\/resultpercentagecalculator","abstract":[{"text":"Performs percentage operations on ","type":"text"},{"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CalculationResult","isActive":true},{"text":" objects","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultPercentageCalculator","kind":"identifier"}],"title":"ResultPercentageCalculator"},"doc://app.soulver.core/documentation/SoulverCore/CurrencyRateRequest":{"role":"symbol","title":"CurrencyRateRequest","type":"topic","abstract":[{"text":"Wraps the various components of a currency rate lookup request","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CurrencyRateRequest"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyRateRequest","kind":"symbol","url":"\/documentation\/soulvercore\/currencyraterequest","navigatorTitle":[{"kind":"identifier","text":"CurrencyRateRequest"}]},"doc://app.soulver.core/documentation/SoulverCore/ResultOperations":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultOperations","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResultOperations","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/soulvercore\/resultoperations","type":"topic","navigatorTitle":[{"text":"ResultOperations","kind":"identifier"}],"abstract":[{"text":"Performs some handy operations on calculation results","type":"text"}],"title":"ResultOperations"},"doc://app.soulver.core/documentation/SoulverCore/URLFromTokenParser":{"title":"URLFromTokenParser","kind":"symbol","navigatorTitle":[{"text":"URLFromTokenParser","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/URLFromTokenParser","url":"\/documentation\/soulvercore\/urlfromtokenparser","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"URLFromTokenParser","kind":"identifier"}],"type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/NotationPreferences":{"navigatorTitle":[{"text":"NotationPreferences","kind":"identifier"}],"title":"NotationPreferences","abstract":[{"type":"text","text":"Notation in SoulverCore are suffix symbols after a number representing its magnitude"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotationPreferences","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/NotationPreferences","type":"topic","kind":"symbol","url":"\/documentation\/soulvercore\/notationpreferences"},"doc://app.soulver.core/documentation/SoulverCore/Multiplier":{"navigatorTitle":[{"kind":"identifier","text":"Multiplier"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Multiplier","type":"topic","kind":"symbol","title":"Multiplier","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Multiplier","kind":"identifier"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing a multiplier (like 3x)"}],"url":"\/documentation\/soulvercore\/multiplier"},"doc://app.soulver.core/documentation/SoulverCore/ECBCurrencyRateProvider":{"navigatorTitle":[{"text":"ECBCurrencyRateProvider","kind":"identifier"}],"title":"ECBCurrencyRateProvider","abstract":[{"type":"text","text":"Currency rate provider that fetches 33 common currency rates from the European Central Bank, no API key required"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ECBCurrencyRateProvider","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ECBCurrencyRateProvider","kind":"symbol","type":"topic","url":"\/documentation\/soulvercore\/ecbcurrencyrateprovider"},"doc://app.soulver.core/documentation/SoulverCore/DateParsing":{"abstract":[{"text":"Add a natural language date scheduling feature to your Mac or iOS calendar or reminders app","type":"text"}],"url":"\/documentation\/soulvercore\/dateparsing","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DateParsing","type":"topic","role":"article","kind":"article","title":"Natural language date parsing"},"doc://app.soulver.core/documentation/SoulverCore/Laptime":{"navigatorTitle":[{"kind":"identifier","text":"Laptime"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Laptime","kind":"symbol","title":"Laptime","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Laptime"}],"abstract":[{"type":"text","text":"A SoulverCore datatype representing the time taken to complete a lap"}],"url":"\/documentation\/soulvercore\/laptime"},"doc://app.soulver.core/documentation/SoulverCore/OctalNumberFromTokenParser":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OctalNumberFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OctalNumberFromTokenParser"}],"url":"\/documentation\/soulvercore\/octalnumberfromtokenparser","title":"OctalNumberFromTokenParser","role":"symbol","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/OctalNumberFromTokenParser"},"doc://app.soulver.core/documentation/SoulverCore/ResultConversionRule":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ResultConversionRule","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultConversionRule","abstract":[{"type":"text","text":"Various conversion rules you can add to the ResultConversionBehavior.withRules"}],"title":"ResultConversionRule","url":"\/documentation\/soulvercore\/resultconversionrule","navigatorTitle":[{"kind":"identifier","text":"ResultConversionRule"}]},"doc://app.soulver.core/documentation/SoulverCore/List":{"navigatorTitle":[{"kind":"identifier","text":"List"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/List","kind":"symbol","title":"List","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"List","kind":"identifier"}],"url":"\/documentation\/soulvercore\/list","abstract":[{"type":"text","text":"A SoulverCore datatype representing a list of evaluation values"}]},"doc://app.soulver.core/documentation/SoulverCore/TokenTypeSet":{"navigatorTitle":[{"kind":"identifier","text":"TokenTypeSet"}],"title":"TokenTypeSet","abstract":[{"text":"A set of token types","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TokenTypeSet","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenTypeSet","type":"topic","kind":"symbol","url":"\/documentation\/soulvercore\/tokentypeset"},"SoulverCoreIcon.png":{"alt":"The icon for SoulverCore","type":"image","identifier":"SoulverCoreIcon.png","variants":[{"traits":["1x","light"],"url":"\/images\/SoulverCoreIcon.png"}]},"doc://app.soulver.core/documentation/SoulverCore/WeatherDataRequest":{"navigatorTitle":[{"text":"WeatherDataRequest","kind":"identifier"}],"title":"WeatherDataRequest","abstract":[{"type":"text","text":"Wraps the various components of a weather data lookup request"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"WeatherDataRequest","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/WeatherDataRequest","type":"topic","kind":"symbol","url":"\/documentation\/soulvercore\/weatherdatarequest"},"doc://app.soulver.core/documentation/SoulverCore/CurrencyCode":{"title":"CurrencyCode","abstract":[{"type":"text","text":"A string that represents a ISO 4217 standard currency code (USD, BTC, SHIB, etc)"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CurrencyCode","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CurrencyCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CurrencyCode"}],"url":"\/documentation\/soulvercore\/currencycode"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionArchiver":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LineCollectionArchiver","kind":"identifier"}],"abstract":[{"type":"text","text":"Archives\/unarchives a "},{"isActive":true,"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection","type":"reference"}],"navigatorTitle":[{"text":"LineCollectionArchiver","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionArchiver","title":"LineCollectionArchiver","url":"\/documentation\/soulvercore\/linecollectionarchiver"},"doc://app.soulver.core/documentation/SoulverCore/CustomFunctionDefinitionUtility":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomFunctionDefinitionUtility"}],"url":"\/documentation\/soulvercore\/customfunctiondefinitionutility","type":"topic","role":"symbol","kind":"symbol","title":"CustomFunctionDefinitionUtility","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionDefinitionUtility","abstract":[{"type":"text","text":"Utility class that supports a UI for creating custom functions"}],"navigatorTitle":[{"kind":"identifier","text":"CustomFunctionDefinitionUtility"}]},"doc://app.soulver.core/documentation/SoulverCore/LineIndex":{"url":"\/documentation\/soulvercore\/lineindex","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"LineIndex","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineIndex","title":"LineIndex","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"LineIndex","kind":"identifier"}],"abstract":[{"text":"Represents the index of a line in a line sheet or collection","type":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/EngineCustomization":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EngineCustomization"}],"kind":"symbol","abstract":[{"type":"text","text":"A key SoulverCore model object used to customize how you want SoulverCore to interpret expressions"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineCustomization","role":"symbol","type":"topic","title":"EngineCustomization","navigatorTitle":[{"kind":"identifier","text":"EngineCustomization"}],"url":"\/documentation\/soulvercore\/enginecustomization"},"doc://app.soulver.core/documentation/SoulverCore/Variable":{"url":"\/documentation\/soulvercore\/variable","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Variable","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Wraps a name\/value pair, where the name will be replaced by the value at parse-time"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Variable"}],"title":"Variable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Variable"}]},"doc://app.soulver.core/documentation/SoulverCore/Calculator":{"abstract":[{"text":"Evaluates a string based math expression","type":"text"}],"role":"symbol","title":"Calculator","url":"\/documentation\/soulvercore\/calculator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Calculator","kind":"identifier"}],"navigatorTitle":[{"text":"Calculator","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Calculator","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/Airport":{"abstract":[{"type":"text","text":"Represents an airport on planet earth"}],"navigatorTitle":[{"text":"Airport","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Airport","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/soulvercore\/airport","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Airport","title":"Airport"},"doc://app.soulver.core/documentation/SoulverCore/ResultContextualMetadata":{"navigatorTitle":[{"kind":"identifier","text":"ResultContextualMetadata"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultContextualMetadata","kind":"symbol","url":"\/documentation\/soulvercore\/resultcontextualmetadata","abstract":[{"type":"text","text":"Provides a human-readable additional information about a particular calculation result"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResultContextualMetadata","kind":"identifier"}],"title":"ResultContextualMetadata"},"doc://app.soulver.core/documentation/SoulverCore/Timestamp":{"url":"\/documentation\/soulvercore\/timestamp","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Timestamp","kind":"identifier"}],"abstract":[{"type":"text","text":"SoulverCore datatype representing a UNIX timestamp."}],"navigatorTitle":[{"kind":"identifier","text":"Timestamp"}],"type":"topic","title":"Timestamp","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Timestamp","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TokenListForm":{"role":"symbol","abstract":[{"text":"Represents some common ‘forms’ a token list might take, and associated data primatives","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TokenListForm","kind":"identifier"}],"url":"\/documentation\/soulvercore\/tokenlistform","navigatorTitle":[{"text":"TokenListForm","kind":"identifier"}],"title":"TokenListForm","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenListForm"},"doc://app.soulver.core/documentation/SoulverCore/TokenType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TokenType"}],"abstract":[{"text":"Represents the different token types found in a math expression","type":"text"}],"kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TokenType","url":"\/documentation\/soulvercore\/tokentype","title":"TokenType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenType"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/PrototypePlaceholder":{"url":"\/documentation\/soulvercore\/prototypeplaceholder","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"PrototypePlaceholder","kind":"identifier"}],"navigatorTitle":[{"text":"PrototypePlaceholder","kind":"identifier"}],"abstract":[{"type":"text","text":"A type placeholder must be a single word with two underscores (__thing, __animal, etc)"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/PrototypePlaceholder","title":"PrototypePlaceholder"},"doc://app.soulver.core/documentation/SoulverCore/CustomFunction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomFunction","kind":"identifier"}],"url":"\/documentation\/soulvercore\/customfunction","title":"CustomFunction","abstract":[{"text":"A custom function is a phrase with a syntax you come up with and a block to provide a result given some parameters","type":"text"}],"navigatorTitle":[{"text":"CustomFunction","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunction"},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionExporter":{"abstract":[{"type":"text","text":"Exports a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollection"},{"type":"text","text":" into a number of plain text formats (CSV, JSON, & plain text)"}],"url":"\/documentation\/soulvercore\/linecollectionexporter","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionExporter","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCollectionExporter"}],"role":"symbol","navigatorTitle":[{"text":"LineCollectionExporter","kind":"identifier"}],"kind":"symbol","title":"LineCollectionExporter"},"doc://app.soulver.core/documentation/SoulverCore/City":{"url":"\/documentation\/soulvercore\/city","title":"City","kind":"symbol","type":"topic","abstract":[{"text":"Represents a city on planet earth","type":"text"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/City","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"City","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"City"}]},"doc://app.soulver.core/documentation/SoulverCore/Scalar":{"url":"\/documentation\/soulvercore\/scalar","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scalar","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Scalar"}],"abstract":[{"type":"text","text":"A string that represents a SI formatted scaling factor to a number"}],"title":"Scalar","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/Scalar"},"doc://app.soulver.core/documentation/SoulverCore/ResultConversionBehavior":{"kind":"symbol","title":"ResultConversionBehavior","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/ResultConversionBehavior","abstract":[{"text":"SoulverCore can automatically convert single results into related forms","type":"text"}],"url":"\/documentation\/soulvercore\/resultconversionbehavior","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultConversionBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"ResultConversionBehavior","kind":"identifier"}],"type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/GettingStarted":{"url":"\/documentation\/soulvercore\/gettingstarted","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"Create a calculator and customize calculation & result formatting"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/GettingStarted","title":"Getting Started with SoulverCore"},"https://soulver.app":{"titleInlineContent":[{"type":"text","text":"Soulver"}],"type":"link","url":"https:\/\/soulver.app","title":"Soulver","identifier":"https:\/\/soulver.app"},"doc://app.soulver.core/documentation/SoulverCore/UnitMeasurementSystem":{"kind":"symbol","url":"\/documentation\/soulvercore\/unitmeasurementsystem","navigatorTitle":[{"text":"UnitMeasurementSystem","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/UnitMeasurementSystem","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnitMeasurementSystem"}],"abstract":[{"type":"text","text":"Standard unit measurement systems you can choose from for your "},{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EngineCustomization","type":"reference","isActive":true}],"type":"topic","title":"UnitMeasurementSystem","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/SubstanceFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/substancefromtokenparser","navigatorTitle":[{"text":"SubstanceFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SubstanceFromTokenParser","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubstanceFromTokenParser"}],"type":"topic","abstract":[],"title":"SubstanceFromTokenParser","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/DependenciesEvaluationAndMergingOperation":{"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DependenciesEvaluationAndMergingOperation","title":"DependenciesEvaluationAndMergingOperation","abstract":[],"role":"symbol","url":"\/documentation\/soulvercore\/dependenciesevaluationandmergingoperation","kind":"symbol","fragments":[{"kind":"identifier","text":"DependenciesEvaluationAndMergingOperation"}]},"doc://app.soulver.core/documentation/SoulverCore/LineCollectionFuser":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineCollectionFuser"}],"abstract":[{"type":"text","text":"A utility class to “fuse” whitespace separated tokens of a type"}],"navigatorTitle":[{"kind":"identifier","text":"LineCollectionFuser"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/LineCollectionFuser","title":"LineCollectionFuser","url":"\/documentation\/soulvercore\/linecollectionfuser"},"doc://app.soulver.core/documentation/SoulverCore/CustomFunctionHandler":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFunctionHandler"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomFunctionHandler"}],"abstract":[{"type":"text","text":"Given a list of parameters, return an evaluation result"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/CustomFunctionHandler","title":"CustomFunctionHandler","url":"\/documentation\/soulvercore\/customfunctionhandler","kind":"symbol","role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore":{"title":"SoulverCore","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","url":"\/documentation\/soulvercore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"role":"collection","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/BooleanFromTokenParser":{"kind":"symbol","url":"\/documentation\/soulvercore\/booleanfromtokenparser","navigatorTitle":[{"text":"BooleanFromTokenParser","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BooleanFromTokenParser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BooleanFromTokenParser","kind":"identifier"}],"type":"topic","abstract":[],"title":"BooleanFromTokenParser","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Introduction","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/GettingStarted"]},{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration"],"title":"Sample projects"},{"title":"Classes","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/AsynchronousOperation","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/BackgroundEvaluationAndMergingOperation","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/DependenciesEvaluationAndMergingOperation"]},{"title":"Variables","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SoulverCoreVersionNumber","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SoulverCoreVersionString"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}