{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The official SoulverCore repo on GitHub includes sample projects for AppKit & UIKit (including Catalyst support) that demonstrate how to integrate SoulverCore into a "},{"code":"NSTextField","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"UITextField"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"MacSampleScreenshot.png","type":"image"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/samplecalculator"]},{"paths":["\/documentation\/soulvercore\/samplecalculator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator"},"kind":"article","metadata":{"title":"Mac & iOS Sample Code","role":"sampleCode","roleHeading":"Sample Code","modules":[{"name":"SoulverCore"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration"],"generated":true,"title":"Sample projects"}],"sampleCodeDownload":{"kind":"sampleDownload","action":{"overridingTitle":"View Source","isActive":true,"type":"reference","identifier":"https:\/\/github.com\/soulverteam\/SoulverCore"}},"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore"]]},"abstract":[{"type":"text","text":"Example of adding a quick calculator feature to a Mac or iOS app"}],"references":{"https://github.com/soulverteam/SoulverCore":{"type":"download","checksum":null,"identifier":"https:\/\/github.com\/soulverteam\/SoulverCore","url":"https:\/\/github.com\/soulverteam\/SoulverCore"},"doc://app.soulver.core/documentation/SoulverCore":{"url":"\/documentation\/soulvercore","title":"SoulverCore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/TextViewIntegration":{"role":"sampleCode","kind":"article","url":"\/documentation\/soulvercore\/textviewintegration","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration","abstract":[{"type":"text","text":"Integrate SoulverCore into the text view of an Mac or iOS app"}],"title":"Add calculation to NSTextView or UITextView"},"MacSampleScreenshot.png":{"alt":"Screenshot from the Mac sample","type":"image","identifier":"MacSampleScreenshot.png","variants":[{"url":"\/images\/MacSampleScreenshot.png","traits":["1x","light"]}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"title":"Sample projects","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}