{"abstract":[{"type":"text","text":"Integrate SoulverCore into the text view of an Mac or iOS app"}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Sample projects","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator"]}],"primaryContentSections":[{"content":[{"text":"Overview","anchor":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"We’ve written a helper package to help you integrate a calculation feature into your "},{"code":"UITextView","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSTextView"},{"text":". See the repository and sample code for more details","type":"text"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"SoulverCore"}],"role":"sampleCode","title":"Add calculation to NSTextView or UITextView","roleHeading":"Sample Code"},"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/TextViewIntegration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore"]]},"variants":[{"paths":["\/documentation\/soulvercore\/textviewintegration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/soulvercore\/textviewintegration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sampleCodeDownload":{"action":{"overridingTitle":"View Source","isActive":true,"type":"reference","identifier":"https:\/\/github.com\/soulverteam\/SoulverTextKit"},"kind":"sampleDownload"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://app.soulver.core/documentation/SoulverCore/SampleCalculator":{"title":"Mac & iOS Sample Code","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator","abstract":[{"text":"Example of adding a quick calculator feature to a Mac or iOS app","type":"text"}],"role":"sampleCode","kind":"article","type":"topic","url":"\/documentation\/soulvercore\/samplecalculator"},"https://github.com/soulverteam/SoulverTextKit":{"type":"download","identifier":"https:\/\/github.com\/soulverteam\/SoulverTextKit","checksum":null,"url":"https:\/\/github.com\/soulverteam\/SoulverTextKit"},"doc://app.soulver.core/documentation/SoulverCore":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","title":"SoulverCore","role":"collection","kind":"symbol","url":"\/documentation\/soulvercore","type":"topic","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/SampleCalculator"],"title":"Sample projects","generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}